name: poly
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- notebook
- jupyter_contrib_nbextensions
- pip
- pip:
  - pandas
  - requests
  - gcsfs
  - google-cloud-firestore
  - transformers
  - datasets
  - huggingface_hub
  - evaluate
